set pages 10000
set line 400
col INST_ID format a5
col NAME format a10
col HOST_NAME format a12
col DB_UNIQUE_NAME format a12
col VERSION format a12
col INSTANCE_NAME format a12
col PRIMARY_DB_UNIQUE_NAME format a12
col OPEN_MODE format a12
col SWITCHOVER_STATUS format a15
col DATABASE_ROLE format a16
col FS_FAILOVER_STATUS format a20

SELECT i.INST_ID I, i.HOST_NAME, i.VERSION, d.DBID, d.NAME, d.DB_UNIQUE_NAME, i.INSTANCE_NAME, d.PRIMARY_DB_UNIQUE_NAME, OPEN_MODE, DATABASE_ROLE, SWITCHOVER_STATUS, FS_FAILOVER_STATUS from GV$DATABASE d join GV$INSTANCE i on d.INST_ID=i.INST_ID;
